# --- Baselines ---

[[sweeps]]
name = "Baseline K-Nearest"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "uniform"
sigma = 0.05
[sweeps.connection_config]
strategy = "k-nearest"
k = 3
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

[[sweeps]]
name = "Baseline Distance"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "uniform"
sigma = 0.05
[sweeps.connection_config]
strategy = "distance"
k = 3
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

# --- Impact of Connectivity ---

[[sweeps]]
name = "Connectivity K-Nearest (k=2)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "uniform"
sigma = 0.05
[sweeps.connection_config]
strategy = "k-nearest"
k = 2
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

[[sweeps]]
name = "Connectivity K-Nearest (k=4)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "uniform"
sigma = 0.05
[sweeps.connection_config]
strategy = "k-nearest"
k = 4
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

[[sweeps]]
name = "Connectivity Distance (d=0.175)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "uniform"
sigma = 0.05
[sweeps.connection_config]
strategy = "distance"
k = 3
d = 0.175
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

[[sweeps]]
name = "Connectivity Distance (d=0.225)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "uniform"
sigma = 0.05
[sweeps.connection_config]
strategy = "distance"
k = 3
d = 0.225
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

# --- Impact of Pathfinding Heuristic ---

[[sweeps]]
name = "Heuristic Joint-Space (K-Nearest)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "uniform"
sigma = 0.05
[sweeps.connection_config]
strategy = "k-nearest"
k = 3
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "joint-space"
num_restarts = 100

[[sweeps]]
name = "Heuristic Joint-Space (Distance)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "uniform"
sigma = 0.05
[sweeps.connection_config]
strategy = "distance"
k = 3
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "joint-space"
num_restarts = 100

# --- Impact of Cycle Avoidance ---

[[sweeps]]
name = "Cycle Avoidance True (K-Nearest)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "uniform"
sigma = 0.05
[sweeps.connection_config]
strategy = "k-nearest"
k = 3
d = 0.2
avoidCycles = true
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

[[sweeps]]
name = "Cycle Avoidance True (Distance)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "uniform"
sigma = 0.05
[sweeps.connection_config]
strategy = "distance"
k = 3
d = 0.2
avoidCycles = true
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

# --- Impact of Sampling Density ---

[[sweeps]]
name = "Density 50 (K-Nearest)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 50
sampling_strategy = "uniform"
sigma = 0.05
[sweeps.connection_config]
strategy = "k-nearest"
k = 3
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

[[sweeps]]
name = "Density 50 (Distance)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 50
sampling_strategy = "uniform"
sigma = 0.05
[sweeps.connection_config]
strategy = "distance"
k = 3
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

[[sweeps]]
name = "Density 200 (K-Nearest)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 200
sampling_strategy = "uniform"
sigma = 0.05
[sweeps.connection_config]
strategy = "k-nearest"
k = 3
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

[[sweeps]]
name = "Density 200 (Distance)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 200
sampling_strategy = "uniform"
sigma = 0.05
[sweeps.connection_config]
strategy = "distance"
k = 3
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

# --- Impact of Sampling Strategy ---

[[sweeps]]
name = "Sampling Gaussian (sigma=0.04) (K-Nearest)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "gaussian"
sigma = 0.04
[sweeps.connection_config]
strategy = "k-nearest"
k = 3
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

[[sweeps]]
name = "Sampling Gaussian (sigma=0.04) (Distance)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "gaussian"
sigma = 0.04
[sweeps.connection_config]
strategy = "distance"
k = 3
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

[[sweeps]]
name = "Sampling Gaussian (sigma=0.05) (K-Nearest)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "gaussian"
sigma = 0.05
[sweeps.connection_config]
strategy = "k-nearest"
k = 3
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

[[sweeps]]
name = "Sampling Gaussian (sigma=0.05) (Distance)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "gaussian"
sigma = 0.05
[sweeps.connection_config]
strategy = "distance"
k = 3
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

[[sweeps]]
name = "Sampling Gaussian (sigma=0.06) (K-Nearest)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "gaussian"
sigma = 0.06
[sweeps.connection_config]
strategy = "k-nearest"
k = 3
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

[[sweeps]]
name = "Sampling Gaussian (sigma=0.06) (Distance)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "gaussian"
sigma = 0.06
[sweeps.connection_config]
strategy = "distance"
k = 3
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

[[sweeps]]
name = "Sampling Bridge (sigma=0.04) (K-Nearest)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "bridge"
sigma = 0.04
[sweeps.connection_config]
strategy = "k-nearest"
k = 3
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

[[sweeps]]
name = "Sampling Bridge (sigma=0.04) (Distance)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "bridge"
sigma = 0.04
[sweeps.connection_config]
strategy = "distance"
k = 3
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

[[sweeps]]
name = "Sampling Bridge (sigma=0.05) (K-Nearest)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "bridge"
sigma = 0.05
[sweeps.connection_config]
strategy = "k-nearest"
k = 3
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

[[sweeps]]
name = "Sampling Bridge (sigma=0.05) (Distance)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "bridge"
sigma = 0.05
[sweeps.connection_config]
strategy = "distance"
k = 3
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

[[sweeps]]
name = "Sampling Bridge (sigma=0.06) (K-Nearest)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "bridge"
sigma = 0.06
[sweeps.connection_config]
strategy = "k-nearest"
k = 3
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

[[sweeps]]
name = "Sampling Bridge (sigma=0.06) (Distance)"
prm_generations = 1000
paths_per_prm = 1000
robot_config_file = "robot.json"
obstacle_config_file = "obstacles.json"
[sweeps.sampling_config]
num_samples = 100
sampling_strategy = "bridge"
sigma = 0.06
[sweeps.connection_config]
strategy = "distance"
k = 3
d = 0.2
avoidCycles = false
[sweeps.planning_config]
heuristic = "none"
num_restarts = 100

